# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cys_qH_CBYxyNl8ZbrMj-WL2VDZ1YRPm
"""

idade1 = 20

idade2 = 35

idade1 + idade2

idade1 - idade2

idade1 * idade2

idade1 / idade2

idade1 + 10

idade1 - 15

idade1 * 4

idade1 / 5

2 * idade1 + 3 * idade2 / 4

(2 * idade1 + 3 * idade2) / 4

idade1 ** 2

15 ** 2

idade2 // idade1

idade2 / idade1

idade2 % idade1

nome = "Glewbber"
sobrenome = "Junior"

print(nome + sobrenome)

print('Olá ', nome, '\n', 'você tem ', idade1 + 15, 'anos.')

input_nome = input('Digite o seu nome: ')